version: "3.9"

services:
  # ------------------- API GATEWAY -------------------
  api-gateway:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: blog_api_gateway
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      SERVICE_NAME: api-gateway

      # Redis (rate limiting, cache)
      REDIS_HOST: redis
      REDIS_PORT: 6379

      # Kafka (events / logs)
      KAFKA_BROKERS: kafka:19092

    ports:
      - "80:5000" # Public HTTP
    depends_on:
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy

    command: ["node", "dist/index.js"]

  # ------------------- REDIS -------------------
  redis:
    image: redis:8
    container_name: blog_api_gateway_redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ------------------- KAFKA (KRaft) -------------------
  kafka:
    image: confluentinc/cp-kafka:7.9.1
    container_name: blog_api_gateway_kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
      - "9093:9093"

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@blog_api_gateway_kafka:9093"

      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:19092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://blog_api_gateway_kafka:19092,PLAINTEXT_HOST://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT"

      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_LOG_RETENTION_HOURS: 168

    volumes:
      - kafka-data:/var/lib/kafka/data

    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  kafka-data:
